## This configuration was generated by terraform-provider-oci

resource oci_functions_application export_baggage-tracking-demo {
  compartment_id = var.compartment_ocid
  config = {
    "NOSQL_COMPARTMENT_ID" = var.compartment_ocid
    "NOSQL_REGION"         = var.region
  }
  defined_tags = {
  }
  display_name = "baggage-tracking-demo"
  freeform_tags = {
  }
  subnet_ids = [
    oci_core_subnet.export_Public-Subnet-vcn_baggage-tracking-demo.id,
  ]
  syslog_url = ""
  trace_config {
    domain_id  = ""
    is_enabled = "false"
  }
}

resource oci_functions_function export_query-api {
  depends_on     = [null_resource.query-apiPush2OCIR]
  application_id = oci_functions_application.export_baggage-tracking-demo.id
  config = {
  }
  defined_tags = {
  }
  display_name = "query-api"
  freeform_tags = {
  }
  image              = "${local.ocir_docker_repository}/${local.ocir_namespace}/${var.ocir_repo_name}/query-api:0.0.1"
  memory_in_mbs      = "256"
  timeout_in_seconds = "120"
  trace_config {
    is_enabled = "false"
  }
}

resource oci_functions_function export_data-keyval-load {
  depends_on     = [null_resource.data-keyval-loadPush2OCIR]
  application_id = oci_functions_application.export_baggage-tracking-demo.id
  config = {
  }
  defined_tags = {
  }
  display_name = "data-keyval-load"
  freeform_tags = {
  }
  image              = "${local.ocir_docker_repository}/${local.ocir_namespace}/${var.ocir_repo_name}/data-keyval-load:0.0.1"
  memory_in_mbs      = "256"
  timeout_in_seconds = "120"
  trace_config {
    is_enabled = "false"
  }
}

resource oci_functions_function export_data-load {
  depends_on     = [null_resource.data-loadPush2OCIR]
  application_id = oci_functions_application.export_baggage-tracking-demo.id
  config = {
  }
  defined_tags = {
  }
  display_name = "data-load"
  freeform_tags = {
  }
  image              = "${local.ocir_docker_repository}/${local.ocir_namespace}/${var.ocir_repo_name}/data-load:0.0.1"
  memory_in_mbs      = "256"
  timeout_in_seconds = "120"
  trace_config {
    is_enabled = "false"
  }
}


